s ='''
Symbol	Description	Score	Functions	Links
GI		0.8043150559054465	circadian rhythm, long-day photoperiodism, long-day photoperiodism, flowering, nucleoplasm, photoperiodism, photoperiodism, flowering, positive regulation of developmental process, positive regulation of multicellular organismal process, positive regulation of post-embryonic development, regulation of circadian rhythm, regulation of post-embryonic development, regulation of reproductive process, response to cold, response to red or far red light, rhythmic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=838883
SPY		0.018317119522775094	negative regulation of cellular process, regulation of reactive oxygen species metabolic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=820327
SPL11		0.012705985720942281		http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=839625
ADO1		0.0068202911810613664	acid-amino acid ligase activity, circadian rhythm, ligase activity, forming carbon-nitrogen bonds, photoperiodism, regulation of circadian rhythm, response to red or far red light, rhythmic process, small conjugating protein ligase activity, ubiquitin-protein ligase activity	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=835842
TEM1		0.006465548461743298	photoperiodism, photoperiodism, flowering, vegetative to reproductive phase transition of meristem	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=839143
ADO3		0.006429393553884666	acid-amino acid ligase activity, circadian rhythm, ligase activity, forming carbon-nitrogen bonds, positive regulation of developmental process, positive regulation of multicellular organismal process, positive regulation of post-embryonic development, regulation of flower development, regulation of post-embryonic development, regulation of reproductive process, regulation of shoot system development, regulatory region DNA binding, regulatory region nucleic acid binding, rhythmic process, small conjugating protein ligase activity, transcription regulatory region DNA binding, ubiquitin-protein ligase activity	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=843133
RAV2		0.006303969102322282	negative regulation of cellular macromolecule biosynthetic process, negative regulation of cellular process, negative regulation of gene expression, negative regulation of macromolecule biosynthetic process, negative regulation of macromolecule metabolic process, negative regulation of metabolic process, negative regulation of nitrogen compound metabolic process, negative regulation of nucleobase-containing compound metabolic process, negative regulation of RNA biosynthetic process, negative regulation of RNA metabolic process, negative regulation of transcription, DNA-templated	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=843216
ADO2		0.006142152311682747	acid-amino acid ligase activity, circadian rhythm, ligase activity, forming carbon-nitrogen bonds, nucleoplasm, regulation of circadian rhythm, rhythmic process, small conjugating protein ligase activity, ubiquitin-protein ligase activity	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=816408
FLC		0.005813746047901414	circadian rhythm, negative regulation of developmental process, negative regulation of flower development, negative regulation of multicellular organismal process, negative regulation of post-embryonic development, negative regulation of reproductive process, regulation of circadian rhythm, regulation of flower development, regulation of post-embryonic development, regulation of reproductive process, regulation of shoot system development, response to cold, rhythmic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=830878
SVP		0.005378861948364733	negative regulation of cellular macromolecule biosynthetic process, negative regulation of cellular process, negative regulation of developmental process, negative regulation of flower development, negative regulation of gene expression, negative regulation of macromolecule biosynthetic process, negative regulation of macromolecule metabolic process, negative regulation of metabolic process, negative regulation of multicellular organismal process, negative regulation of nitrogen compound metabolic process, negative regulation of nucleobase-containing compound metabolic process, negative regulation of post-embryonic development, negative regulation of reproductive process, negative regulation of RNA biosynthetic process, negative regulation of RNA metabolic process, negative regulation of transcription, DNA-templated, regulation of flower development, regulation of post-embryonic development, regulation of reproductive process, regulation of shoot system development	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=816787
RFI2		0.0052148385852794354	acid-amino acid ligase activity, ligase activity, forming carbon-nitrogen bonds, small conjugating protein ligase activity, ubiquitin-protein ligase activity	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=819383
CDF1		0.0039739629879416705	negative regulation of cellular macromolecule biosynthetic process, negative regulation of cellular process, negative regulation of gene expression, negative regulation of macromolecule biosynthetic process, negative regulation of macromolecule metabolic process, negative regulation of metabolic process, negative regulation of nitrogen compound metabolic process, negative regulation of nucleobase-containing compound metabolic process, negative regulation of RNA biosynthetic process, negative regulation of RNA metabolic process, negative regulation of transcription, DNA-templated	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=836364
LHY		0.002464225852588431	circadian rhythm, long-day photoperiodism, long-day photoperiodism, flowering, photoperiodism, photoperiodism, flowering, regulation of circadian rhythm, regulatory region DNA binding, regulatory region nucleic acid binding, response to cold, rhythmic process, transcription regulatory region DNA binding, vegetative to reproductive phase transition of meristem	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=839341
APRR1		0.002457361084879539	circadian rhythm, negative regulation of gene expression, negative regulation of macromolecule metabolic process, negative regulation of metabolic process, rhythmic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=836259
CO		0.0024373389332988382	circadian rhythm, regulation of flower development, regulation of post-embryonic development, regulation of reproductive process, regulation of shoot system development, response to red or far red light, rhythmic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=831441
TIC		0.002101254953354448	circadian rhythm, regulation of circadian rhythm, rhythmic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=821807
FT		0.0018492673666165582	photoperiodism, photoperiodism, flowering, positive regulation of developmental process, positive regulation of multicellular organismal process, positive regulation of post-embryonic development, regulation of flower development, regulation of post-embryonic development, regulation of reproductive process, regulation of shoot system development, regulation of stomatal movement, stomatal movement, vegetative to reproductive phase transition of meristem	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=842859
COP1		0.0017774688130191563	acid-amino acid ligase activity, circadian rhythm, ligase activity, forming carbon-nitrogen bonds, nucleoplasm, photoperiodism, photoperiodism, flowering, regulation of circadian rhythm, regulation of stomatal movement, response to red or far red light, rhythmic process, small conjugating protein ligase activity, stomatal movement, ubiquitin-protein ligase activity, vegetative to reproductive phase transition of meristem	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=817857
EFS		0.001587847477641402	carotenoid metabolic process, negative regulation of developmental process, negative regulation of flower development, negative regulation of multicellular organismal process, negative regulation of post-embryonic development, negative regulation of reproductive process, regulation of flower development, regulation of post-embryonic development, regulation of reproductive process, regulation of shoot system development, tetraterpenoid metabolic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=844066
ABA4		0.0009041207989248234	carotenoid metabolic process, regulation of reactive oxygen species metabolic process, tetraterpenoid metabolic process	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=843028
ELF3		0.0006975790026594875	circadian rhythm, photoperiodism, photoperiodism, flowering, regulation of flower development, regulation of post-embryonic development, regulation of reproductive process, regulation of shoot system development, regulation of stomatal movement, response to cold, response to red or far red light, rhythmic process, stomatal movement, vegetative to reproductive phase transition of meristem	http://www.ncbi.nlm.nih.gov/sites/entrez?db=gene&cmd=search&term=817134
'''.strip()



import pandas as pd
import io
df = pd.read_csv(io.StringIO(s),sep='\t')
import requests

import re
import urllib.request
def get_gene_id(link):
	print((link,))
	buf = urllib.request.urlopen(link).read().decode('utf8')
	res = re.findall('Araport:([a-zA-Z0-9]*)',buf)[0]
	return res
res = get_gene_id(df['Links'][0])

df.insert(0,'gene_id',['NA']*len(df))
df['gene_id'] = list(map(get_gene_id,df['Links']))
df.to_csv('gm.csv')
# print(res)
# print(df['Links'].values)
